action(type="omfwd"
        queue.filename="fwd.queue"
        queue.maxdiskspace="1g"
        queue.saveonshutdown="on"
        queue.type="LinkedList"
        action.resumeRetryCount="-1"
        Target="otelcol1" Port="54526" Protocol="tcp")